[phases.setup]
nixPkgs = ['nodejs']

[phases.install]
cmds = [
  'npm run install:server',
  'npm run install:client'
]

[phases.build]
cmds = [
  'cd client && CI=false npm run build',
  'cd server && npm run build',
  'cp -r client/dist server/dist/public'
]

[start]
cmd = 'npm start'

[variables]
NODE_ENV = 'production'
CI = 'false'