[phases.setup]
nixPkgs = ['nodejs', 'pnpm']

[phases.install]
cmds = [
  'pnpm install --frozen-lockfile',
  'cd server && pnpm install --frozen-lockfile',
  'cd client && pnpm install --frozen-lockfile'
]

[phases.build]
cmds = [
  'cd server && pnpm run build',
  'cd client && pnpm run build',
  'cp -r client/dist server/dist/public'
]

[start]
cmd = 'cd server && node dist/server.js'

[variables]
NODE_ENV = 'production'