[phases.setup]
nixPkgs = ['nodejs', 'npm']

[phases.install]
cmds = [
  'npm install',
  'cd server && npm install',
  'cd client && npm install'
]

[phases.build]
cmds = [
  'cd server && npm run build',
  'cd client && npm run build',
  'cp -r client/dist server/dist/public'
]

[start]
cmd = 'cd server && node dist/server.js'

[variables]
NODE_ENV = 'production'