[phases.setup]
nixPkgs = ['nodejs']

[phases.install]
cmds = [
  'npm run install:server',
  'npm run install:client'
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm start'

[variables]
NODE_ENV = 'production'